version: '2'

services:
  mariadb:
    image: bitnami/mariadb:latest
    ports:
      - '3306:3306'
    volumes:
      - './data/mariadb:/bitnami/mariadb'
      - './logs/mariadb:/opt/bitnami/mariadb/logs'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  apache:
    image: bitnami/apache:latest
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './conf/apache:/opt/bitnami/apache/conf/vhosts/'
      - './logs/apache:/opt/bitnami/apache/logs'
      - './app:/app'
      
  php-fpm:
    build: ./dockerfiles/php5.6
    image: disappointedmoose/php-fpm:5.6
    ports:
      - "35729:35729"
    depends_on:
      - mariadb
    volumes:
      - './conf/php/100-custom.ini:/opt/bitnami/php/etc/conf.d/100-custom.ini'
      - './logs/php:/opt/bitnami/php/logs'
      - './app:/app'
      - './data/composer:/usr/sbin/.composer'
      - './data/composer-root:/root/.composer'

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mariadb
    ports:
      - '81:80'

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.33.0.0/16